### ISSUE TITLE
hw1 makefile question

### ISSUE THREAD

**Issue by littlehug** [SytemProgramming2015FallatNTU/Announcement#16]
因為用c++寫的，發現好像不太適用原來的makefile，
請問可以自行在 src 生成另一個 makefile嗎?
另外程式名稱必須是 file_merger.c 嗎?
因為沒有用到 include 資料夾裡的東西，那是不是這些東西不能留著呢?
謝謝!!

**Comment by younger50** [comment]
1. 建議將原本[Makefile](https://github.com/SytemProgramming2015FallatNTU/SP15MP1/blob/master/src/Makefile)中的變數"GCC"的值由"gcc"改為"g++"。
2. 只需確保你在"src"下的Makefile會在"make"指令後會由原始碼編譯後在"bin"下生成"file_merger"的執行檔。
3. 程式附檔名可更改為".cpp"。
4. 若仍能滿足2. 可自行更改"include"內的檔案。

**Comment by littlehug** [comment]
Thanks!
