### ISSUE TITLE
port_register error

### ISSUE THREAD

**Issue by hsnusonic** [SytemProgramming2015FallatNTU/Announcement#18]
我只有執行
```
./port_register &
```
就跑出
port bind error
server init failed

想請問助教可能的問題是什麼呢？

**Comment by cchao** [comment]
That means the port for listening is occupied. (Maybe there's other `port_register` launched by someone else.)
If you want to use it, you need to change the `default_register_port` in [this header](https://github.com/SytemProgramming2015FallatNTU/SP15MP2/blob/master/include/connect.h#L8) to some number in [1024, 65535], or maybe you can use the `port_register` launched by someone else.
