### ISSUE TITLE
send and recv

### ISSUE THREAD

**Issue by MarkYan** [SytemProgramming2015FallatNTU/Announcement#36]
我在client send＿message 一個path 過去，並且在server recv_message。
send 的時候只有 .gitignore , server卻收到 ./gitignoergrad/01/b01502069...... 一長串字。
我在send的時候都是用PATH_MAX長度來傳, 也會先memset成0, 該free的也都有free掉。

**Comment by chishengshih** [comment]
Your message is a request for debugging, not clarifing the assignment. 

To ask for assistant on debugging on internet, 
1. Find the right place to post and here is not the right place. 
2. Post part of your source code, which is now allowed on this site. 

My suggestion is to discuss this issue with TA or classmate in personal or via email.

**Comment by MarkYan** [comment]
okay~
